import Head from 'next/head'
import Header from '../components/header'
import Nav from "../components/Nav"
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({ props }) {
  return (
    <div >
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results result={props} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const gener = context.query.gener;
  const res = await fetch(
    `https://api.themoviedb.org/3${requests[gener]?.url || requests.fetchTrending.url}`)
  const data = await res.json()
  return {
    props: {
      result: data
    }
  };
}
