import Head from 'next/head'
import Header from '../components/header'
import Nav from "../components/Nav"
import Results from '../components/Results'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results />

    </div>
  )
}

export async function getServerSideProps(context) {

}
